language: node_js
node_js: 8
cache:
  yarn: true
  directories:
  - node_modules
  - "${NVM_PATH}_modules"
  - "$HOME/google-cloud-sdk/"
install:
- yarn
- cd functions && yarn && cd ..
script:
- yarn lint
- echo "Building..."
- yarn build:prod
before_deploy:
- echo "Deploying!"
- openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv -in serviceAccount.json.enc -out serviceAccount.json -d
- yarn firebase functions:config:set mailchimp.listid=$MAILCHIMP_LIST_ID --token $FIREBASE_TOKEN
- yarn firebase functions:config:set mailchimp.dc=$MAILCHIMP_DC --token $FIREBASE_TOKEN
- yarn firebase functions:config:set mailchimp.apikey=$MAILCHIMP_API_KEY --token $FIREBASE_TOKEN
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: master
  project: devfesttoulouse-2018
  token:
    secure: LABmBBESq7RnCsmqAMY2aMTgvtBQqlJ9p0sA+rIvBfdIn07dCBE0XzxMfvE3E4HvMub4WtfmiOm0fdwwGBBNr8UlHwozVtl4epmlKqkvV+bQcZx8qMW+rJ3e1ba3nlKGpoRbWkGm/yoW9gq1cKsXPpOtIsTVE+ZRQKrNKnCj2oLjZWguBs0QSvf27q5AE6oF6Za1cycwu0MMgbGPtUk6qVwmIReGFxUrCdwfNDokxMHUfa9wxixuo5MpECVekfWTmUW231ShI2BSVP/rp4MQhJXCYkHBlEmEBYQgpbJN2djn8wajfvxoXN2qbyOA+GcSeaMag9rCOO2DOOaaP+cSBLtHM44vVXk8HL/5t8z2M7oI6Ag6kJVr9pIjTAo7O+M+fhE9uxffD8QzC8Zgp5w0BU/+EHO1cZ5gBC/Cw4rKhPm8eMvJQx29DlGb0pIXW/E3ZUmF+7AWjpWr0whuH3wLlKSdlBnsQ7B/eXlUW3GpgOCq0UxSQUW1qidpZZg9IBUZ7yomTg0MwwS9RxiZQvG6TjNGsrAGIMX1hV9ldBq7Dox653utyRZKLdwtBi38MVawwJH6wsR5PQ6HozMbvKVcTBaSbZAqw6yLSlE+HzW456r8JJ5JQe6lzcVBit4SImFFZGSAd5S7FVY2gus6NolVM69G5jtfKxb73MAJ8qw5bEA=
after_deploy:
- echo "Deploying Database"
- yarn firebase firestore:delete -r -y blog
- yarn firebase firestore:delete -r -y partners
- yarn firebase firestore:delete -r -y schedule
- yarn firebase firestore:delete -r -y sessions
- yarn firebase firestore:delete -r -y speakers
- yarn firebase firestore:delete -r -y team
- yarn firebase firestore:delete -r -y tickets
- yarn firebase firestore:delete -r -y videos
- yarn firestore:ci:update
env:
  global:
  - secure: JG4hXJwJpr6sqR5n3ICtAsLzba9uMN5mIzYVmRVZZJ8IY/YQizp2nHLQYjxTO49XnnEezEwYXvySWVcYIrOtLNNOEEpzLdXGWK046OSviLnFYPWp+Q6HHSszE/Bosc4mYO1MWt+ZlN2swCcjmmWsP1SHf5icXpPqSzyZbyvulY9lZbzFHjDtYnsQ69AT0ZGc/XyqpxpDLZ5CTrySlBioFUj8d7Z+yLIFHduPq5GzEz6tJpa9wbengNH70luMNLwQGZsYSR1t4SGvPmpJKN7GUZqSK8oHILFy8k7jPRmxbcGDHwAbL0tA6VTu+d5Jpg30ILcBrpoyp1ql8tDgs5/9UieRj+ZEhF0ncYmkiwNY9JiNtEDjrcCYpNgXn1qxVQB9W+1QcC6tgWY5G9/HEg4zq2qyIOVh4h+Tg5t2ROo4qIQy9ojoNJm3r/g0l2ABx3/kudE33mVFZDJjfdRjrW/rlDG8EbSZdj9YHtUe991xfcYGi9ksxMe7b1ZsvGI2TY79xceGHvyi8af8HsYXNvCjkQ2pJETc0+W7whaH+lik/JiZVyFEGcn5Om4I27PjPFHgTwhZXORvRZHE7uxB2jJo2IsU3kNL/qM9eD2rx5J/fUue2p0oC9ZEjMhHUiGJoyb5TsCtxKizVjhFM78KlS5Bee7/jMldxAWAbuuiPeILvlQ=
  - secure: LShbBupIJr67s2cTEZpfBKcjYapXDzDYGsdVhSyKBmS4U10OyCGdijiE0vwapnzxcn++8kB1rh9YcIRNYtHbI0EYZJuxCKfLOdxbNR+othM1+V4k4H/B4ZeF+tRMyn/nC00Jz08F1wflpkh/8US1bn1eTBEmMTLMMkiYIm+QcaYXchch9GlFMXShfM0777CyYuKb1quULU1LuBS2vcjuS3e/BCiz1taS1PmVI8ntKJMpE+Pon1cWBxqLoMC3ivhPQFx2ZGvF7+C0hY06WddCQ4WqVeUBlPneyCFoPLf0R7Wox8MJ0xIlIzYwXM3yNSfW5tgWGtrEAZI+TVGFwY0Wt1J9oTvO3Z9ICWjVtJfqG8o/KaXovWbxQ67O+SvHsixTcqkfg9wYxDCJH31cNol8+HpI3TiKLQGHlzblSJ8g+I4kKDOGttVI5jKe46KOIhpOyEkQBqtx3NCJjlJsFarWjeGW08m3Nu6UeKMgPQoPFyUk7xzjp3dtwzGz2qES4eLUe6yiQbbCKTks0fozz9w7+9cwC/h4nBzfuIIXOkcVKIaqO7poX1ALCDpqdRyW0Slak+ocs223jmnUQnmRTMRyZPYw8jd2ZGGKJGPFfB5fTgIg8C6bKQslRCiDoyxdNrnj4Yfyf7hZPJNQMbYLoD6tQhPLedKdEdWFaLVtIVMdfhU=
  - secure: d3OBfco/rAc1vgSjLSB3jneF91Ig8pJ2oyJXslP/o/5zibC2Y8M7Zkx0grfQGPoyZeunBsShJpEPMF9n5Dun1qr2hpFGhRQ2fMSB2+w0Z/GaKSQvC8Dx96TCA/HMjYU0TmyKX/lbA1GSBLM5LGNcmCJln8irYZ7+tuLieoLtUo6BdAAUxLaTqLzZc3V27aCyxQlMouz2KUjNfGMyYT5H2hFAwgd8OqKubCKDIZJpogtCr19zVyFDqqEbM635C8LMFH51X8/oXlugwKW6ZiVx8X6od8KKdwp9Z53n7ju8HWY71UbG+ZLW2NnupjuaDi4Aygl1PG1mfWWo6Rt4MywqDf59ssCcTkMLJNUNaxSNzDMY1ICCPWwyvRipBV9RVgByoZ3n71nLPxvqpycENgaTXvcfxhPhfj7n4WHItVYi0UY99hgINZqt59bWyV9xluXlX3hFQMsuf1pblkv0g+z974DDrqs4MM7jBX2EHPVaYho+lE5ziHTYQcGaQCWLd4Hx4CmY5GLU5q69FQXabU4vTuxBNHvuXPxHFaHvDA3Di6GB/xX1uI9mlYUOV3t/d91h/vOXjwXsE6bbTnWdPr/P7l2Dj7Y2lk30pO+MNjaIkaEtdwmgMz7w024jq9z/uIc7Mi/GRlzh/qFCdwfK5WVjHAeRM3Rq4m4w9CJWXZKuh48=
  - secure: TmW0cm+Vx6Pnw1cD6KKMEH1LyyFd46Qn0m/cDXgwbl6M4r5YmZvSkMeRLKGAPN/fB0J6fz9LsPhGQOJpRt94JdFdFt2K1RNzoK103qQaT461wHwNoRIFAAicG3M9FcbeS5jM8PE5Nsa84f9uan7bFK+7l1AGilc3lwfkkqf8WlM/xChLCtMl3BvuTqYJ4PlWSddfmcizJYvMT0/T8s6wh5C7tEQl9MnVC2CToCu7Rg5Nyp1uWxUUQEMc04U+kUxaYWhQcAI5w08IQoT6+kwMCYhTXU3oYQhOa0uzzU/OGhNcrSSv4POMjE0gF1Yy07/oomRgr3paUqA/JFXjBXFdmlDWjnPLEAmDmA0TUvm2fsfNPlpuDRhzJpeZWEIw9/9jnoFkV5AJM5khbafMmfXCmHinbq6OFWblJ2gVK/A/tvvXlaN4qyJeWWwn5w/ocZhf7T2dvqpFyP3p89p5NXtMNGksWkM9Th87QtMdTlr1Ym49F1NEj3O/1+AOOioGaFZAmNqikSyFnoinXiLEz2GiwwbmkZeYD5/mwm0dxY37zXIDRu7TM4g/fl/pVZik98ZKGZV/hUXwE9X+KXdeoOCUt6K0CFlucabfS6aH+2m3mXBiAlRBpoOsM7VDs6XazXkVaf0MNxsHpDB0P+KP89UNlFf3sTCtKyamklPucusWD+4=
