language: node_js
node_js: 8
cache:
  yarn: true
  directories:
  - node_modules
  - "${NVM_PATH}_modules"
  - "$HOME/google-cloud-sdk/"
install:
- yarn
- cd functions && yarn && cd ..
script:
- yarn lint
- echo "Building..."
- yarn build:prod
before_deploy:
- echo "Deploying!"
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: master
  project: devfesttoulouse-2018
  token:
    secure: LABmBBESq7RnCsmqAMY2aMTgvtBQqlJ9p0sA+rIvBfdIn07dCBE0XzxMfvE3E4HvMub4WtfmiOm0fdwwGBBNr8UlHwozVtl4epmlKqkvV+bQcZx8qMW+rJ3e1ba3nlKGpoRbWkGm/yoW9gq1cKsXPpOtIsTVE+ZRQKrNKnCj2oLjZWguBs0QSvf27q5AE6oF6Za1cycwu0MMgbGPtUk6qVwmIReGFxUrCdwfNDokxMHUfa9wxixuo5MpECVekfWTmUW231ShI2BSVP/rp4MQhJXCYkHBlEmEBYQgpbJN2djn8wajfvxoXN2qbyOA+GcSeaMag9rCOO2DOOaaP+cSBLtHM44vVXk8HL/5t8z2M7oI6Ag6kJVr9pIjTAo7O+M+fhE9uxffD8QzC8Zgp5w0BU/+EHO1cZ5gBC/Cw4rKhPm8eMvJQx29DlGb0pIXW/E3ZUmF+7AWjpWr0whuH3wLlKSdlBnsQ7B/eXlUW3GpgOCq0UxSQUW1qidpZZg9IBUZ7yomTg0MwwS9RxiZQvG6TjNGsrAGIMX1hV9ldBq7Dox653utyRZKLdwtBi38MVawwJH6wsR5PQ6HozMbvKVcTBaSbZAqw6yLSlE+HzW456r8JJ5JQe6lzcVBit4SImFFZGSAd5S7FVY2gus6NolVM69G5jtfKxb73MAJ8qw5bEA=
after_deploy:
- echo "Deploying Database"
- jq '.blog' data/firebase-data.json | firebase database:set -y /blog --token $FIREBASE_TOKEN
- jq '.partners' data/firebase-data.json | firebase database:set -y /partners --token $FIREBASE_TOKEN
- jq '.schedule' data/firebase-data.json | firebase database:set -y /schedule --token $FIREBASE_TOKEN
- jq '.sessions' data/firebase-data.json | firebase database:set -y /sessions --token $FIREBASE_TOKEN
- jq '.speakers' data/firebase-data.json | firebase database:set -y /speakers --token $FIREBASE_TOKEN
- jq '.team' data/firebase-data.json | firebase database:set -y /team --token $FIREBASE_TOKEN
- jq '.tickets' data/firebase-data.json | firebase database:set -y /tickets --token $FIREBASE_TOKEN
- jq '.videos' data/firebase-data.json | firebase database:set -y /videos --token $FIREBASE_TOKEN
env:
  global:
    secure: JG4hXJwJpr6sqR5n3ICtAsLzba9uMN5mIzYVmRVZZJ8IY/YQizp2nHLQYjxTO49XnnEezEwYXvySWVcYIrOtLNNOEEpzLdXGWK046OSviLnFYPWp+Q6HHSszE/Bosc4mYO1MWt+ZlN2swCcjmmWsP1SHf5icXpPqSzyZbyvulY9lZbzFHjDtYnsQ69AT0ZGc/XyqpxpDLZ5CTrySlBioFUj8d7Z+yLIFHduPq5GzEz6tJpa9wbengNH70luMNLwQGZsYSR1t4SGvPmpJKN7GUZqSK8oHILFy8k7jPRmxbcGDHwAbL0tA6VTu+d5Jpg30ILcBrpoyp1ql8tDgs5/9UieRj+ZEhF0ncYmkiwNY9JiNtEDjrcCYpNgXn1qxVQB9W+1QcC6tgWY5G9/HEg4zq2qyIOVh4h+Tg5t2ROo4qIQy9ojoNJm3r/g0l2ABx3/kudE33mVFZDJjfdRjrW/rlDG8EbSZdj9YHtUe991xfcYGi9ksxMe7b1ZsvGI2TY79xceGHvyi8af8HsYXNvCjkQ2pJETc0+W7whaH+lik/JiZVyFEGcn5Om4I27PjPFHgTwhZXORvRZHE7uxB2jJo2IsU3kNL/qM9eD2rx5J/fUue2p0oC9ZEjMhHUiGJoyb5TsCtxKizVjhFM78KlS5Bee7/jMldxAWAbuuiPeILvlQ=
